// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: external.proto

#include "external.pb.h"
#include "external.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace external {

static const char* External_method_names[] = {
  "/external.External/Put",
  "/external.External/Get",
  "/external.External/TellLeader",
};

std::unique_ptr< External::Stub> External::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< External::Stub> stub(new External::Stub(channel));
  return stub;
}

External::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(External_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(External_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TellLeader_(External_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status External::Stub::Put(::grpc::ClientContext* context, const ::external::PutRequest& request, ::external::PutReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

void External::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::external::PutRequest* request, ::external::PutReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void External::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::external::PutReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::external::PutReply>* External::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::external::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::external::PutReply>* External::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::external::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, false);
}

::grpc::Status External::Stub::Get(::grpc::ClientContext* context, const ::external::GetRequest& request, ::external::GetReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

void External::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::external::GetRequest* request, ::external::GetReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void External::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::external::GetReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::external::GetReply>* External::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::external::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::external::GetReply>* External::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::external::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, false);
}

::grpc::Status External::Stub::TellLeader(::grpc::ClientContext* context, const ::external::GetRequest& request, ::external::GetReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TellLeader_, context, request, response);
}

void External::Stub::experimental_async::TellLeader(::grpc::ClientContext* context, const ::external::GetRequest* request, ::external::GetReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TellLeader_, context, request, response, std::move(f));
}

void External::Stub::experimental_async::TellLeader(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::external::GetReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TellLeader_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::external::GetReply>* External::Stub::AsyncTellLeaderRaw(::grpc::ClientContext* context, const ::external::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::GetReply>::Create(channel_.get(), cq, rpcmethod_TellLeader_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::external::GetReply>* External::Stub::PrepareAsyncTellLeaderRaw(::grpc::ClientContext* context, const ::external::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::external::GetReply>::Create(channel_.get(), cq, rpcmethod_TellLeader_, context, request, false);
}

External::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::external::PutRequest, ::external::PutReply>(
          std::mem_fn(&External::Service::Put), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::external::GetRequest, ::external::GetReply>(
          std::mem_fn(&External::Service::Get), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::external::GetRequest, ::external::GetReply>(
          std::mem_fn(&External::Service::TellLeader), this)));
}

External::Service::~Service() {
}

::grpc::Status External::Service::Put(::grpc::ServerContext* context, const ::external::PutRequest* request, ::external::PutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status External::Service::Get(::grpc::ServerContext* context, const ::external::GetRequest* request, ::external::GetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status External::Service::TellLeader(::grpc::ServerContext* context, const ::external::GetRequest* request, ::external::GetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace external

